#include <stdio.h>

#define DOCTYPE "<!DOCTYPE html>\n"
#define HTMLSTART "<html>\n"
#define BODYSTART "<body>\n"
#define BODYEND "</body>\n"
#define HTMLEND "</html>\n"
#define BREAKTAG "<br>\n"
#define PARASTART "<p>"
#define PARAEND "</p>\n"
#define HTMLSPACE "&nbsp"
#define FONTEND "</font>"
#define FONTCOLOUR "<font color ="
#define ENDBRACE ">"
#define REDCOLOUR "red"
#define GREENCOLOUR "green"
#define BLUECOLOUR "blue"
#define YELLOWCOLOUR "yellow"
#define MAGENTACOLOUR "magenta"
#define CYANCOLOUR "cyan"
#define WHITECOLOUR "white"
#define BLACKCOLOUR "black"
#define STYLESTART "<style> body "
#define BCOLOUR "{background-color: black}"
#define FCOLOUR "{colour: white}"
#define STYLEEND "</style>\n"
#define SPANSTART "<span "
#define SPANEND "</span>"
#define STYLECOLOUR "style = color:"
#define STYLE "style = "
#define SPANBCOLOUR "background-color:"

void create_html(cell teleTextCells[][COL]);
